# -*- coding: utf-8 -*-
"""Practica_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yEoxD6q2BH1KGPlOkS8ETMIpV0IKW69K
"""

class ModuloAdquisicionConocimiento:
    def __init__(self):
        self.base_conocimiento = {}

    def agregar_conocimiento(self, pregunta, respuesta):
        self.base_conocimiento[pregunta.lower()] = respuesta

    def buscar_respuesta(self, pregunta):
        pregunta = pregunta.lower()
        return self.base_conocimiento.get(pregunta, "Lo siento, no tengo información sobre eso.")

class ChatSencillo:
    def __init__(self):
        self.adquisicion_conocimiento = ModuloAdquisicionConocimiento()

    def cargar_conocimiento_inicial(self):
        conocimiento_inicial = {
            "hola": "¡Hola! ¿De que te gustaría hablar?",
            "como estas": "Estoy bien. ¿Y tú?",
            "tambien bien": "Me da gusto, ¿En que puedo ayudarte?",
            "¿En que mes estamos?": "En marzo",
            "¿De que color es el cielo?": "Azul"
        }
        for pregunta, respuesta in conocimiento_inicial.items():
            self.adquisicion_conocimiento.agregar_conocimiento(pregunta, respuesta)

    def iniciar_conversacion(self):
        print("¡Bienvenido!")
        while True:
            input_usuario = input("Usuario: ")
            if input_usuario.lower() == "salir":
                print("¡Hasta luego!")
                break
            respuesta_chat = self.adquisicion_conocimiento.buscar_respuesta(input_usuario)
            if "Lo siento" in respuesta_chat:  # Si el bot no tiene información
                print("Bot:", respuesta_chat)
                respuesta_usuario = input("Bot: ¿Cuál es tu respuesta a esa pregunta? ")
                print("Bot: ¡Gracias por compartir tu conocimiento!")
            else:
                print("Bot:", respuesta_chat)

# Crear una instancia del chat sencillo
chat = ChatSencillo()

# Cargar conocimiento inicial
chat.cargar_conocimiento_inicial()

# Iniciar la conversación
chat.iniciar_conversacion()